version: '3.8'

services:
  JAQp_db:
    image: 'postgres:latest'
    container_name: JAQp_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=JAQp
    ports:
      - "5433:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
#     - ./schema:/docker-entrypoint-initdb.d   
  JAQp_minio:
    image: minio/minio
    ports:
          - "9000:9000"
          - "9001:9001"
    volumes:
          - minio-data:/data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: miniominio 
    command: server --console-address ":9001" /data
            
volumes:
  pg-data:
  minio-data:
  