name: CI
  on:
    pull_request:
        branches:
          - master
          - develop
    push: 
        branches:
          - master
          - develop
  jobs:
    java_build_server:
      runs-on: ubuntu-latest
      env:
        working-directory: ./JAQpApi
      steps:
        - uses: actions/checkout@v3
        - name: Set up JDK 17
          uses: actions/setup-java@v3
          with:
            java-version: '17'
            distribution: 'temurin'
            cache: maven
        - name: Build with Maven
          run: mvn -B package --file pom.xml
          working-directory: ${{env.working-directory}}
#        - name: Move package
#          run: cp ./target/*.jar ../Docker/api/
#          working-directory: ${{env.working-directory}}
#        - name: Commit and push build
#          uses: devops-infra/action-commit-push@v0.9.2
#          with:
#            github_token: ${{ secrets.GIT_TOKEN }}
#            commit_prefix: "[AUTO-COMMIT]"
#            commit_message: "server jar moved to Docker"
# Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
